defaultSettings:
  defaultDataPath: /var/lib/longhorn/data-1
  defaultReplicateCount: 1
  defaultDataLocality: best-effort

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
  defaultFsType: ext4

service:
  ui:
    type: ClusterIP

longhornUI:
  replicas: 1

longhornManager:
  log:
    format: json

longhornDriver:
  log:
    format: json
